on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Rust binary
        run: cargo build --release
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-binary
          path: target/release/my-binary

  download:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-binary
      - name: Set executable permissions
        run: chmod +x my-binary
      - name: Run binary
        run: ./my-binary